version: '3.9'
services:
  postgres-master:
    image: postgres:14-alpine 
    ports:
      - 5432:5432
    volumes:
      - ./master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./master/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./master/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rizkidb
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  
  postgres-replica:
    image: postgres:14-alpine
    user: postgres
    ports:
      - 5433:5432
    command: |
      bash -c "
      pg_basebackup --pgdata=/var/lib/postgresql/data --host=postgres-master --port=5432 --slot=replicationslot --username=replicator --no-password
      echo 'Replication established'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - postgres-master
    
    